#!/bin/bash
ip link set $1 down
iwconfig $1 mode managed
ip link set $1 up
#iw wlx00c0caaaf863 set channel 6 HT40-
#iw wlx00c0caaaf863 set freq 5745 80 5775
#iw wlx00c0caaaf863 set txpower fixed 3000
